In [3]:
import pandas as pd

sample = pd.read_csv("내국인 생활인구.csv", encoding='cp949')
sample

,일자(stdr_de_id),시간(tmzon_pd_se),행정동코드(adstrd_code_se),집계구코드(oa_cd),생활인구합계(tot_lvpop_co),남자0~9세(male_f0t9_lvpop_co),남자10~14세(male_f10t14_lvpop_co),남자15~19세(male_f15t19_lvpop_co),남자20~24세(male_f20t24_lvpop_co),남자25~29세(male_f25t29_lvpop_co),...,여자40~44세(female_f40t44_lvpop_co),여자45~49세(female_f45t49_lvpop_co),여자50~54세(female_f50t54_lvpop_co),여자55~59세(female_f55t59_lvpop_co),여자60~64세(female_f60t64_lvpop_co),여자65~69세(female_f65t69_lvpop_co),여자70~74세(female_f70t74_lvpop_co),여자75~79세(female_f75t79_lvpop_co),여자80세이상(female_above_80_lvpop_co),등록일자(ldadng_dt)
0,20170226,4,11320515,1125061020007,4.3097,11.9781,8.2257,1.8759,4.2075,6.2647,...,9.0816,52.6711,24.9152,3.6202,91.3448,13.6818,45.2880,2.3141,9.7668,2021-08-17 16:06:44
1,20180107,22,11380510,1115071010309,338.3900,23.2446,3.1141,1.9972,2.6983,0.1240,...,10.0707,9.9150,14.6710,29.2192,0.1533,36.7707,0.9227,4.6111,18.1781,2021-08-17 16:06:44
2,20180317,6,11680610,1113073020101,1805.5256,4.3720,324.3596,10.8350,12.1324,20.4938,...,28.8794,19.4895,1.6087,16.2525,8.1640,34.3989,3.4030,3.8434,4.4772,2021-08-17 16:06:44
3,20190222,7,11305575,1106071020403,504.4956,14.0599,14.3256,3.5239,19.3154,6.8197,...,0.2650,36.5731,14.3217,35.7359,7.2808,6.9919,27.4321,1.8361,7.7510,2021-08-17 16:06:44
4,20210706,6,11740660,1107073040015,744.6219,0.5662,2.9824,2.9719,31.0868,7.2338,...,39.7471,1.5230,47.5514,63.4768,52.3638,35.3496,32.1275,85.6665,95.0249,2021-08-17 16:06:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,20170603,7,11650560,1122057010104,465.8914,16.4274,4.2056,11.2869,3.5184,14.1803,...,17.2636,4.9406,16.3334,26.8672,1.0048,3.5458,18.9442,13.5570,17.3543,2021-08-17 16:06:44
496,20211007,5,11620525,1111056061002,180.1291,12.6887,8.1278,2.1684,23.3810,5.5894,...,9.7934,23.8109,10.2240,28.3686,9.9961,7.2371,5.7134,15.6473,6.1426,2021-08-17 16:06:44
497,20200819,20,11140635,1121078010101,540.8267,0.7004,14.3413,2.9791,0.2832,13.5837,...,0.0017,13.7260,14.1506,46.9632,10.5080,8.6825,3.9238,3.3179,13.5500,2021-08-17 16:06:44
498,20171011,11,11590605,1121082010004,992.2594,35.4771,8.4071,17.8773,1.2632,1.8164,...,3.9551,28.8403,10.7913,33.7729,1.4717,8.7947,8.5835,9.3403,0.0000,2021-08-17 16:06:44
499,20200725,21,11350625,1115053030001,1098.0798,12.6300,12.6652,18.6522,275.4479,20.0665,...,63.2687,18.9043,36.0630,27.1679,18.4721,13.1369,21.8967,6.0132,4.8362,2021-08-17 16:06:44

In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

# score_array를 오름차순으로 정렬했을 때의 인덱스를 반환
sort_indices_asc = np.argsort(score_array)

print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

In [3]:
import pandas as pd

titanic_df = pd.read_csv("titanic_train.csv")
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [29]:
import pandas as pd

data = {'Name': ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
}

data_df = pd.DataFrame(data, index=[1,2,3,4])
data_df

       Name  Year  Gender
1   Chulmin  2011    Male
2  Eunkyung  2016  Female
3  Jinwoong  2015    Male
4   Soobeom  2015    Male

In [39]:
drop_data = data_df[data_df['Gender'] != 'Female']
drop_data

       Name  Year Gender
1   Chulmin  2011   Male
3  Jinwoong  2015   Male
4   Soobeom  2015   Male